env:
  matrix:
    - TRAVIS_PYTHON_VERSION="2.7"
  global:
    secure: fQDopgWxen7KDFRdI1vjZDUh2cV6+MOY1pqeht410uTq9HynLoWduzPN65FV7rxcGSN2uWV77GBU0OZKQTb7j1LP7A2o+Z/Usebc/aGAyG0ev9O54ff7ghaG+dfJ0UZ/Fjt1qgD0EVfIBbnc02MgUnkwR2cio0lUBlamel8rZzo=

os:
  - linux
  - osx

sudo: false

before_install:
  - echo "Build on $TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_TAG" == v* ]]; then export BUILD_STR=""; else export BUILD_STR="dev"; fi
  - bash .ci/travis/install_python.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda info -a
  - conda build -q .conda

install:
  - conda install -q basic-modeling-interface --use-local

script:
  - python -c "from basic_modeling_interface import Bmi"

after_success:
  - bash .ci/travis/deploy_to_anaconda.sh
