package:
  name: basic-modeling-interface
  version: {{"0.1.3" + environ.get('BUILD_STR', '')}}

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - basic_modeling_interface

about:
  home: https://github.com/bmi-forum/bmi-python
  license: MIT License
  summary: 'Python bindings for the Basic Modeling Interface'
  license_family: MIT
